### ISSUE TITLE
Confusion about the pretrained models

### ISSUE THREAD

**Issue by RookieZB** [fanolabs/NID_ACLARR2022#2]
您好，我对你们的工作非常感兴趣，这边有两个问题。首先你们论文中说到模型是用Clinc数据做预训练然后再用internal数据训练，为什么这里会提供3个预训练模型，我理解不是应该提供个Clinc的预训练模型？其次想请教下如果没有external数据的话，想复现出图4中的效果是不是把模型路径换成bert-base-uncased即可？再次感谢你们的工作！

**Comment by zhang-yu-wei** [comment]
您好！

感谢您对我们工作感兴趣！我们这里的预训练是通过在external data上有监督训练和internal data上自监督训练（为了适应下游任务的语料）联合完成的（原文公式1）。

其次如果没有external data的话，可以将模型路径改为bert-base-uncased。

Best,
Yuwei Zhang

**Comment by RookieZB** [comment]
感谢答复！我明白您意思了，所以如果想用你们预训练模型复现出论文效果的话，是不是直接跑clnn训练就够了，因为这些模型已经做了mtp预训练了？另外还有个小问题请教下，请问你们有没有单独在Clinc数据（将其作为internal）上验证过clnn模型效果呢？

谢谢！
@zhang-yu-wei

**Comment by zhang-yu-wei** [comment]
我们提供的模型包含了外部数据训练的阶段，其余的训练阶段可以follow我们的code。

另外，我们的paper主要focus在将CLINC作为外部数据的setting，来探究对target domain的影响，目前还没有做过您的实验。

**Comment by RookieZB** [comment]
@zhang-yu-wei 好的，非常感谢你们的工作和答复！
